### ISSUE TITLE
Delay in delivery of messages

### ISSUE THREAD

**Issue by vertisan** [inspircd/inspircd-docker#105]
Hi,
I am looking for an IRC-based solution that will replace online chat that will be able to support several dozen thousand people at the same time. I tried with different options but still, 4-5 messages arrive immediately and the rest are delayed.
Below is my current config, something else I should change to get this effect?
https://pastebin.com/WPV59UjM

**Comment by SISheogorath** [comment]
Hi,

Have you checked that the clients yo uare using are not throttling the
messages? This is something quite typical for IRC and your current
config would simply kill clients that send more than 1 command per
second on average (1 message = 1 command) with an allowed burst rate of
10.

Also notice the `limit` parameter of your connect class that is set to
5000, which means the server will not allow more than 5000 users to
join with this connect class. This might also collides with the max
file sockets of your system configuration.

Please make sure you have a proper understanding of IRC before running
such large services. Since this is an issue tracker, not a support
forum, I recommend to you join #inspircd on irc.inspircd.org instead. I
hope that helps.

On Wed, 2020-03-11 at 05:41 -0700, Paweł Farys wrote:
> Hi,
> I am looking for an IRC-based solution that will replace online chat
> that will be able to support several dozen thousand people at the
> same time. I tried with different options but still, 4-5 messages
> arrive immediately and the rest are delayed.
> Below is my current config, something else I should change to get
> this effect?
> https://pastebin.com/WPV59UjM
> 
-- 
Signed
Sheogorath

OpenPGP: https://shivering-isles.com/openpgp/0xFCB98C2A3EC6F601.txt

**Comment by vertisan** [comment]
Hi,

Thanks for your response, I have already found the issue and it was connection between server and client and now it is ok.
btw. I have 2 more questions: 
* my logging setting looks like this:  
```<log method="file" type="*" level="debug" target="logs/ircd.log">``` but file is not created and I cannot see logs, why?
* How can I output these logs to stdout? I'm using it by Docker image so I want to "catch" them all into docker and next forward where I need.
